### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by nielsvanvelzen** [unveloper/slf4j-timber#3]
Thanks for creating this library, I'm currently looking into updating an Android app and it's libraries to use SLF4j 2.x. Unfortunately our current SLF4j implementation using Timber isn't supported anymore (in fact; you're the only one with support for 2.x!).
One limitation for us it that we only allow libraries from Maven Central and the official Google repository. Not Jitpack.

Are you planning to publish your library to Maven Central?

**Comment by unveloper** [comment]
Hi Niels!
I'm glad you appreciate this library (give it a star if you like it :) )

Publish it to Maven Central can be nice, I'll look into it!

**Comment by unveloper** [comment]
@nielsvanvelzen done!
The artifact has moved from **com.github.unveloper:slf4j-timber** to **io.github.unveloper:slf4j-timber**

Enjoy :)

**Comment by nielsvanvelzen** [comment]
Thanks! It works as expected
